version: '3'

services:
  ngtpass:
    build:
      context: https://github.com/ngttech/ngtpass.git
      args:
        - BUILDKIT_INLINE_CACHE=0
    container_name: ngtpass
    ports:
      - "5000:5000"
    restart: unless-stopped
    # Removing the problematic volume mounts 