version: '3'

services:
  ngtpass:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ngtpass
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./app.py:/app/app.py
      - ./password_generator.py:/app/password_generator.py
      - ./static:/app/static
      - ./templates:/app/templates 